In [1]:
!pip install mediapipe

In [60]:
from imblearn.over_sampling import SMOTE
import sklearn
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from numpy.linalg import norm
from sklearn.metrics.pairwise import cosine_similarity

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

import mediapipe as mp
import cv2
import os
from xgboost import XGBClassifier
from tqdm import tqdm

import pickle

In [61]:
def print_metrics(y_true, y_pred, name):
    print(25*"##")
    print(name)
    print("Accuracy:",accuracy_score(y_test_list,y_pred))
    print("F1 Score:",f1_score(y_test_list,y_pred, average="weighted"))
    print(25*"##")
    
def run_models(x_train, x_test, y_train, y_test, custom):
    
    model_dict = {}
    
    ## logistic regression
    model_logistic = LogisticRegression()
    model_logistic.fit(x_train,y_train)
    y_pred = model_logistic.predict(x_test)
    print(25*"##")
    print("LOGISTIC REGRESSION")
    print("Testing Data:")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("F1 Score:",f1_score(y_test,y_pred, average="weighted"))
    #print(classification_report(y_test,y_pred))
    #print(25*"**")
    y_pred = model_logistic.predict(x_train)
    print(25*"--")
    print("Training Data:")
    print("Accuracy:",accuracy_score(y_train,y_pred))
    print("F1 Score:",f1_score(y_train,y_pred, average="weighted"))
    ##print(classification_report(y_train,y_pred))
    
    ## SGD classifier
    model_SGD = SGDClassifier()
    model_SGD.fit(x_train,y_train)
    y_pred = model_SGD.predict(x_test)
    print(25*"##")
    print("SGD CLASSIFIER")
    print("Testing Data:")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("F1 Score:",f1_score(y_test,y_pred, average="weighted"))
    #print(classification_report(y_test,y_pred))
    #print(25*"**")
    y_pred = model_SGD.predict(x_train)
    print(25*"--")
    print("Training Data:")
    print("Accuracy:",accuracy_score(y_train,y_pred))
    print("F1 Score:",f1_score(y_train,y_pred, average="weighted"))
    ##print(classification_report(y_train,y_pred))
    
    ## Naive Bayes
    model_NB = GaussianNB()
    model_NB.fit(x_train,y_train)
    y_pred = model_NB.predict(x_test)
    print(25*"##")
    print("GAUSSIAN NAIVE BAYES")
    print("Testing Data:")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("F1 Score:",f1_score(y_test,y_pred, average="weighted"))
    #print(classification_report(y_test,y_pred))
    #print(25*"**")
    y_pred = model_NB.predict(x_train)
    print(25*"--")
    print("Training Data:")
    print("Accuracy:",accuracy_score(y_train,y_pred))
    print("F1 Score:",f1_score(y_train,y_pred, average="weighted"))
    ##print(classification_report(y_train,y_pred))
    
    ## Random Forest
    model_RF = RandomForestClassifier()
    model_RF.fit(x_train,y_train)
    y_pred = model_RF.predict(x_test)
    print(25*"##")
    print("RANDOM FOREST")
    print("Testing Data:")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("F1 Score:",f1_score(y_test,y_pred, average="weighted"))
    #print(classification_report(y_test,y_pred))
    #print(25*"**")
    y_pred = model_RF.predict(x_train)
    print(25*"--")
    print("Training Data:")
    print("Accuracy:",accuracy_score(y_train,y_pred))
    print("F1 Score:",f1_score(y_train,y_pred, average="weighted"))
    ##print(classification_report(y_train,y_pred))
    
    ## XGBoost
    model_xgboost = XGBClassifier()
    model_xgboost.fit(x_train,y_train)
    y_pred = model_xgboost.predict(x_test)
    print(25*"##")
    print("XGBOOST")
    print("Testing Data:")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("F1 Score:",f1_score(y_test,y_pred, average="weighted"))
    #print(classification_report(y_test,y_pred))
    #print(25*"**")
    y_pred = model_xgboost.predict(x_train)
    print(25*"--")
    print("Training Data:")
    print("Accuracy:",accuracy_score(y_train,y_pred))
    print("F1 Score:",f1_score(y_train,y_pred, average="weighted"))
    ##print(classification_report(y_train,y_pred))
    
    ## AdaBoost
    model_adaboost = AdaBoostClassifier()
    model_adaboost.fit(x_train,y_train)
    y_pred = model_adaboost.predict(x_test)
    print(25*"##")
    print("ADABOOST")
    print("Testing Data:")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("F1 Score:",f1_score(y_test,y_pred, average="weighted"))
    #print(classification_report(y_test,y_pred))
    #print(25*"**")
    y_pred = model_adaboost.predict(x_train)
    print(25*"--")
    print("Training Data:")
    print("Accuracy:",accuracy_score(y_train,y_pred))
    print("F1 Score:",f1_score(y_train,y_pred, average="weighted"))
    ##print(classification_report(y_train,y_pred))
    
    ## KNN
    model_knn = KNeighborsClassifier()
    model_knn.fit(x_train,y_train)
    y_pred = model_knn.predict(x_test)
    print(25*"##")
    print("KNN CLASSIFIER")
    print("Testing Data:")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("F1 Score:",f1_score(y_test,y_pred, average="weighted"))
    #print(classification_report(y_test,y_pred))
    #print(25*"**")
    y_pred = model_knn.predict(x_train)
    print(25*"--")
    print("Training Data:")
    print("Accuracy:",accuracy_score(y_train,y_pred))
    print("F1 Score:",f1_score(y_train,y_pred, average="weighted"))
    ##print(classification_report(y_train,y_pred))
    
    ## SVM
    model_SVM = SVC()
    model_SVM.fit(x_train,y_train)
    y_pred = model_SVM.predict(x_test)
    print(25*"##")
    print("SVM")
    print("Testing Data:")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("F1 Score:",f1_score(y_test,y_pred, average="weighted"))
    #print(classification_report(y_test,y_pred))
    #print(25*"**")
    y_pred = model_SVM.predict(x_train)
    print(25*"--")
    print("Training Data:")
    print("Accuracy:",accuracy_score(y_train,y_pred))
    print("F1 Score:",f1_score(y_train,y_pred, average="weighted"))
    ##print(classification_report(y_train,y_pred))

    model_dict["logistic"] = model_logistic
    model_dict["SGD"] = model_SGD
    model_dict["RF"] = model_RF
    model_dict["KNN"] = model_knn
    model_dict["SVM"] = model_SVM
    model_dict["XGB"] = model_xgboost
    model_dict["ADA"] = model_adaboost
    model_dict["NB"] = model_NB
    
    name = "raw_feature_model_dict"
    if custom:
        name = "custom_feature_model_dict.pkl"
    
    with open(name,"wb") as handle:
        pickle.dump(model_dict, handle, protocol=pickle.HIGHEST_PROTOCOL)
        
    return model_dict

In [108]:
def get_cosine_similarity_results(x_train, x_test, y_train, y_test, features):
    #print(x_train[:10])
    #print(y_train[:10])
    y_pred = []
    
    dataset = pd.concat([x_train, y_train], axis=1)
    dict1 = {} #pose -> 132 size array with mean keypoints

    for pose in range(0,81):
      temp = dataset.loc[dataset['label'] == pose].mean()
      temp = temp.drop(labels=['label'])
      dict1[pose] = temp
    #print(dict1)
    
    with open("cosine_dict.pkl","wb") as handle:
        pickle.dump(dict1,handle)
        
    feature_wise_cosine_similarity = {} ## i'th data_point -> {}
    
    feature_wise_cosine_similarity["data_point"] = []
    feature_wise_cosine_similarity["actual_pose"] = []
    feature_wise_cosine_similarity["predicted_pose"] = []
    
    for i in tqdm(range(x_test.shape[0])):

        curr_row = [x_test.iloc[i]]

        curr_y = -1
        curr_sim_score = -float("inf")

        for pose in range(0,81):
          row = dict1[pose]
          #print(row)
          #print("----")
          #print(curr_row)
          row = row.to_numpy()
          curr_row = np.array(curr_row)
          sim_score = cosine_similarity(row.reshape(1, -1),curr_row.reshape(1,-1))

          if sim_score > curr_sim_score:
            curr_sim_score = sim_score
            curr_y = pose

        """for j in range(x_train.shape[0]):

            row = [x_train.iloc[j,:]]

            sim_score = cosine_similarity(row,curr_row)

            if sim_score > curr_sim_score:
                curr_sim_score = sim_score
                curr_y = y_train.iloc[j]"""
        
        feature_wise_cosine_similarity["data_point"].append(i)
        feature_wise_cosine_similarity["predicted_pose"].append(le.inverse_transform([curr_y])[0])
        feature_wise_cosine_similarity["actual_pose"].append(le.inverse_transform([list(y_test)[i]])[0])
        
        row = dict1[curr_y]
        for j in range(len(features)-1):
            
            if features[j] not in feature_wise_cosine_similarity:
                feature_wise_cosine_similarity[features[j]] = []
                
            n1 = row[j]
            n2 = curr_row[0][j]
            sim = 1 - abs(n1 - n2) / (n1 + n2)
            feature_wise_cosine_similarity[features[j]] = sim
        
        y_pred.append(curr_y)

    y_test_list = list(y_test)
    
    print(25*"##")
    print("COSINE SIMILARITY RESULTS:")
    print("Accuracy:",accuracy_score(y_test_list,y_pred))
    print("F1 Score:",f1_score(y_test_list,y_pred, average="weighted"))
    
    correction_df = pd.DataFrame(feature_wise_cosine_similarity)
    
    if len(features) >= 100:
        correction_df.to_csv("correction_dataframe_raw.csv")
    else:
        correction_df.to_csv("correction_dataframe_custom.csv")
    
    print(25*"##")
    
    
def cosine_eval(x_test, y_test, y_pred, features):
    #print(x_train[:10])
    #print(y_train[:10])
    
    with open("cosine_dict.pkl","rb") as handle:
        dict1 = pickle.load(handle)
        
    feature_wise_cosine_similarity = {} ## i'th data_point -> {}
    
    feature_wise_cosine_similarity["data_point"] = []
    feature_wise_cosine_similarity["actual_pose"] = []
    feature_wise_cosine_similarity["predicted_pose"] = []
    
    for i in tqdm(range(x_test.shape[0])):

        curr_row = [x_test.iloc[i]]
      
        feature_wise_cosine_similarity["data_point"].append(i)
        
        feature_wise_cosine_similarity["predicted_pose"].append(le.inverse_transform([y_pred[i]])[0])
        feature_wise_cosine_similarity["actual_pose"].append(le.inverse_transform([list(y_test)[i]])[0])
        
        row = dict1[y_pred[i]]
        for j in range(len(features)-1):
            
            if features[j] not in feature_wise_cosine_similarity:
                feature_wise_cosine_similarity[features[j]] = []
                
            n1 = row[j]
            n2 = curr_row[0][j]
            sim = 1 - abs(n1 - n2) / (n1 + n2)
            feature_wise_cosine_similarity[features[j]] = sim
        

    y_test_list = list(y_test)
    
    print("dataframe saved with eval results!!")
    
    correction_df = pd.DataFrame(feature_wise_cosine_similarity)
    
    if len(features) >= 100:
        correction_df.to_csv("correction_dataframe_raw.csv")
    else:
        correction_df.to_csv("correction_dataframe_custom.csv") 

In [63]:
def get_raw_data_results(df):
    
    ## converting output to numeric values
    le.fit(df["Pose"])
    df["label"] = le.transform(df["Pose"])
    
    ## dropping Pose column
    df.drop(columns=["Pose","ImgNum"],inplace=True)
    
    ## feature designing for train and test
    df #= get_designed_data_df(df)
    
    x = df.iloc[:,:-1]
    y = df.iloc[:,-1]
    
    x_train, x_test, y_train, y_test = train_test_split(x,y,stratify=y,test_size=0.25, random_state=0)

    """dataset = pd.concat([x_train, y_train], axis=1)
    dict1 = {} #pose -> 132 size array with mean keypoints

    for pose in range(0,81):
      temp = dataset.loc[dataset['label'] == pose].mean()
      dict1[pose] = temp
    print(dict1)"""

    
    ## running different models on this
    #model_dict = run_models(x_train, x_test, y_train, y_test,False)
    
    #return model_dict
    ## get cosine similarity results
    get_cosine_similarity_results(x_train, x_test, y_train, y_test, df.columns)

In [38]:
le = preprocessing.LabelEncoder()
df = pd.read_csv("trainSet_yoga82.csv")
get_raw_data_results(df)

100%|██████████| 3879/3879 [01:02<00:00, 62.56it/s]


##################################################
COSINE SIMILARITY RESULTS:
Accuracy: 0.277133281773653
F1 Score: 0.2944410321729524
      data_point                                        actual_pose  \
0              0                            Sitting pose 1 (normal)   
1              1  Extended_Revolved_Side_Angle_Pose_or_Utthita_P...   
2              2                     Scorpion_pose_or_vrischikasana   
3              3  Pose_Dedicated_to_the_Sage_Koundinya_or_Eka_Pa...   
4              4                           Supta_Virasana_Vajrasana   
...          ...                                                ...   
3874        3874  Half_Lord_of_the_Fishes_Pose_or_Ardha_Matsyend...   
3875        3875  Standing_big_toe_hold_pose_or_Utthita_Padangus...   
3876        3876                                      Cockerel_Pose   
3877        3877                             Plow_Pose_or_Halasana_   
3878        3878                             Supta_Baddha_Konasana_   

            

In [64]:
def get_angle(p1, p2, p3):
    
    """
        returns angle between p1,p2,p3 with p2 as the pivot
    """
    
    v1 = p1-p2
    v2 = p3-p2
    
    num = np.inner(v1,v2)
    den = (np.sqrt((v1**2).sum())) * (np.sqrt((v2**2).sum()))
    
    return np.degrees(np.arccos(num/den))

def get_designed_data_df(df):
    
    d = {}

    for i in tqdm(range(df.shape[0])):

        j=0
        while j<df.shape[1]-1:

            col_name = df.columns[j].split("-")[0]

            data_point = np.array([df.iloc[i,j], df.iloc[i,j+1], df.iloc[i,j+2]])
            col_name = col_name.lower()

            if col_name not in d:
                d[col_name] = []

            d[col_name].append(data_point)
            j+=4

        if "label" not in d:
            d["label"] = []
        d["label"].append(df.iloc[i,j]) 
        
    return get_custom_features(pd.DataFrame(d))
    
def get_custom_features(df):
    
    ## add features

    d = {}

    ## angles
    d["max_hand_angle"] = []
    d["min_hand_angle"] = []
    d["max_foot_angle"] = []
    d["min_foot_angle"] = []

    d["max_elbow_to_knee_angle"] = []
    d["min_elbow_to_knee_angle"] = []

    d["knee_to_knee_angle"] = []
    d["elbow_to_elbow_angle"] = []

    #d["heel_at_nose_angle"] = []
    #d["hand_at_nose_angle"] = []
    d["max_nose_to_heel_angle"] = []

    ## distances
    d["feet_to_shoulder_ratio"] = []
    d["hand_to_shoulder_ratio"] = []

    for i in tqdm(range(df.shape[0])):

        ## hand angles
        angle1 = get_angle(df["left_wrist"][i], df["left_elbow"][i], df["left_shoulder"][i])
        angle2 = get_angle(df["right_wrist"][i], df["right_elbow"][i], df["right_shoulder"][i])

        d["max_hand_angle"].append(max(angle1,angle2))
        d["min_hand_angle"].append(min(angle1,angle2))

        ## leg angles
        angle1 = get_angle(df["left_ankle"][i], df["left_knee"][i], df["left_hip"][i])
        angle2 = get_angle(df["right_ankle"][i], df["right_knee"][i], df["right_hip"][i])

        d["max_foot_angle"].append(max(angle1,angle2))
        d["min_foot_angle"].append(min(angle1,angle2))

        ## hand to leg angles
        # wrist to leg angle instead of elbow to knee
        angle1 = get_angle(df["left_elbow"][i], df["left_hip"][i], df["left_knee"][i])
        angle2 = get_angle(df["right_elbow"][i], df["right_hip"][i], df["right_knee"][i])
        #angle1 = get_angle(df["left_wrist"][i], df["left_hip"][i], df["left_ankle"][i])
        #angle2 = get_angle(df["right_wrist"][i], df["right_hip"][i], df["right_ankle"][i])

        d["max_elbow_to_knee_angle"].append(max(angle1,angle2))
        d["min_elbow_to_knee_angle"].append(min(angle1,angle2))

        ## elbow to elbow
        # try elbow-centroid-elbow instead
        mid_point = (df["left_shoulder"][i] + df["right_shoulder"][i]) / 2
        angle = get_angle(df["left_elbow"][i], mid_point, df["right_elbow"][i])

        #centroid = np.mean(df.iloc[i])
        #angle = get_angle(df["left_elbow"][i], centroid, df["right_elbow"][i])

        d["elbow_to_elbow_angle"].append(angle)

        ## knee to knee
        mid_point = (df["left_hip"][i] + df["right_hip"][i]) / 2
        angle = get_angle(df["left_knee"][i], mid_point, df["right_knee"][i])

        #angle = get_angle(df["left_knee"][i], centroid, df["right_knee"][i])
        d["knee_to_knee_angle"].append(angle)

        ## heels at nose and hand at nose angle
        # heel-waist-heel instead of heel-nose-heel
        #angle1 = get_angle(df["left_wrist"][i], df["nose"][i], df["right_wrist"][i])
        #angle2 = get_angle(df["left_heel"][i], df["nose"][i], df["right_heel"][i])
        #mid_point = (df["left_hip"][i] + df["right_hip"][i]) / 2
        #angle2 = get_angle(df["left_heel"][i], mid_point, df["right_heel"][i])

        #d["hand_at_nose_angle"].append(angle1)
        #d["heel_at_nose_angle"].append(angle2)

        # nose-waist-heel
        midpoint = (df["left_hip"][i] + df["right_hip"][i]) / 2
        angle1 = get_angle(df["nose"][i], midpoint, df["right_heel"][i])
        angle2 = get_angle(df["nose"][i], midpoint, df["left_heel"][i])

        d["max_nose_to_heel_angle"].append(max(angle1,angle2))

        ############################################
        
        ## centroid distance 
        centroid = np.mean(df.iloc[i])
        incl_cols = ["left_wrist", "left_elbow", "left_shoulder", "left_eye", "left_hip", "left_knee", "left_ankle",
                     "right_wrist", "right_elbow", "right_shoulder", "right_eye", "right_hip", "right_knee", "right_ankle"]
        for col in df.columns:
  
            if col in incl_cols:
                
                name = col+"_centroid_distance"
                if name not in d:
                    d[name] = []

                #print(col, df[col][i])
                d[name].append(np.sqrt(np.sum(np.square(df[col][i]-centroid))))
        
        ## feet and hand to shoulder ratio

        d_shoulder = np.sqrt(np.sum(np.square(df["left_shoulder"][i] - df["right_shoulder"][i])))
        d_hand = np.sqrt(np.sum(np.square(df["left_wrist"][i] - df["right_wrist"][i])))
        d_feet = np.sqrt(np.sum(np.square(df["left_foot_index"][i] - df["right_foot_index"][i])))

        d["feet_to_shoulder_ratio"].append(d_feet/d_shoulder)
        d["hand_to_shoulder_ratio"].append(d_hand/d_shoulder)

    ## output
    if "label" in df:
        d["label"] = df["label"]
    
    return pd.DataFrame(d)

In [82]:
def get_designed_data_results(df):
    
    ## converting output to numeric values
    le.fit(df["Pose"])
    df["label"] = le.transform(df["Pose"])
    
    ## dropping Pose column
    df.drop(columns=["Pose","ImgNum"],inplace=True)
    
   
    ## feature designing for train and test
    df = get_designed_data_df(df)
    
    x = df.iloc[:,:-1]
    y = df.iloc[:,-1]
    
    x_train, x_test, y_train, y_test = train_test_split(x,y,stratify=y,test_size=0.25, random_state=0)
    
    
    
    model_dict = None
    ## run models
    model_dict = run_models(x_train, x_test, y_train, y_test,True)
    
    ## cosine similarity
    get_cosine_similarity_results(x_train, x_test, y_train, y_test, df.columns)
    
    return model_dict

In [110]:
def predict_image(img_path, model, le, design_features):
    
    ## get image keypoints
    mp_pose = mp.solutions.pose
    mp_drawing = mp.solutions.drawing_utils 
    mp_drawing_styles = mp.solutions.drawing_styles

    
    with mp_pose.Pose(static_image_mode=True, min_detection_confidence=0.5, model_complexity=2) as pose:
        
        landmark_names = []
        
        for name in mp_pose.PoseLandmark:
            name = str(name).lower().split(".")[-1]
            landmark_names.append(name)
            
        img = cv2.imread(img_path)
        results = pose.process(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
      
        row = {}
        for i in range(0,33):
            coord = results.pose_landmarks.landmark[i]
  
            if landmark_names[i] not in row:
                row[landmark_names[i]] = []
            
            row[landmark_names[i]].append(np.array([coord.x, coord.y, coord.z]))
        
    df = pd.DataFrame(row)
    
    if design_features:
        
        df = get_custom_features(df)
        
    """
    CAN VISUALIZE AND ADD NOTION OF NOISE CLASS HERE
    """
    
    
    
    y_proba = model.predict_proba(df)
    name = le.inverse_transform(model.predict(df))
    print("predicted_pose:",name)
    print("getting cosine similarity results...")
    y_test = ["" for i in range(df.shape[0])]
    y_pred = model.predict(df)
    
 #   print(y_test)
 #   print(y_pred[0])
 
    cosine_eval(df, [1 for i in range(df.shape[0])], y_pred, df.columns)
       # x_train, df, y_train, ["" for i in range(df.shape[0])], model.predict(df), df.columns)

In [84]:
## cosine similarity on designed features
le = preprocessing.LabelEncoder()
df = pd.read_csv("trainSet_yoga82.csv")
get_designed_data_results(df)

100%|██████████| 15516/15516 [00:16<00:00, 943.00it/s] 
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


##################################################
LOGISTIC REGRESSION
Testing Data:
Accuracy: 0.5158546017014695
F1 Score: 0.4909363250850151
--------------------------------------------------
Training Data:
Accuracy: 0.5305491105955144
F1 Score: 0.5096246665820652
##################################################
SGD CLASSIFIER
Testing Data:
Accuracy: 0.2853828306264501
F1 Score: 0.23108435941885627
--------------------------------------------------
Training Data:
Accuracy: 0.2950073042880467
F1 Score: 0.23885190322656408
##################################################
GAUSSIAN NAIVE BAYES
Testing Data:
Accuracy: 0.8819283320443413
F1 Score: 0.8829747044804347
--------------------------------------------------
Training Data:
Accuracy: 0.8950760505284867
F1 Score: 0.895597338054792
##################################################
RANDOM FOREST
Testing Data:
Accuracy: 0.922918277906677
F1 Score: 0.9224669358946616
--------------------------------------------------
Training Data:


100%|██████████| 3879/3879 [01:13<00:00, 52.87it/s]


##################################################
COSINE SIMILARITY RESULTS:
Accuracy: 0.3663315287445218
F1 Score: 0.3690172163524
##################################################


{'logistic': LogisticRegression(),
 'SGD': SGDClassifier(),
 'RF': RandomForestClassifier(),
 'KNN': KNeighborsClassifier(),
 'SVM': SVC(),
 'XGB': XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
               colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
               early_stopping_rounds=None, enable_categorical=False,
               eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
               importance_type=None, interaction_constraints='',
               learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
               max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
               missing=nan, monotone_constraints='()', n_estimators=100,
               n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
               predictor='auto', random_state=0, reg_alpha=0, ...),
 'ADA': AdaBoostClassifier(),
 'NB': GaussianNB()}

In [ ]:
! gdown --id 18WNBVg98h_JKXCSKaZDELalBXZkvExI3

In [ ]:
le = preprocessing.LabelEncoder()
df = pd.read_csv("trainSet_yoga82.csv")
get_designed_data_results(df)

100%|██████████| 17513/17513 [00:26<00:00, 664.73it/s]
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


##################################################
LOGISTIC REGRESSION
Testing Data:
Accuracy: 0.5172413793103449
F1 Score: 0.4951959748881769
--------------------------------------------------
Training Data:
Accuracy: 0.5266483934825643
F1 Score: 0.5083430772877348
##################################################
SGD CLASSIFIER
Testing Data:
Accuracy: 0.31491208038364926
F1 Score: 0.2840277804901138
--------------------------------------------------
Training Data:
Accuracy: 0.32183645500228414
F1 Score: 0.2909727063599277
##################################################
GAUSSIAN NAIVE BAYES
Testing Data:
Accuracy: 0.8833066910253482
F1 Score: 0.884005508979424
--------------------------------------------------
Training Data:
Accuracy: 0.8934064260697426
F1 Score: 0.8939559353149742
##################################################
RANDOM FOREST
Testing Data:
Accuracy: 0.9282941310801552
F1 Score: 0.9278770392281098
--------------------------------------------------
Training Data:

{'ADA': AdaBoostClassifier(),
 'KNN': KNeighborsClassifier(),
 'NB': GaussianNB(),
 'RF': RandomForestClassifier(),
 'SGD': SGDClassifier(),
 'SVM': SVC(),
 'XGB': XGBClassifier(objective='multi:softprob'),
 'logistic': LogisticRegression()}

In [ ]:
le = preprocessing.LabelEncoder()
df = pd.read_csv("trainSet_yoga82.csv")
get_raw_data_results(df)

In [100]:
le.inverse_transform([y_pred[0]])[0]

'Extended_Revolved_Triangle_Pose_or_Utthita_Trikonasana_'

2. ---

In [115]:
path =  "/home/hardeekh/Downloads/custom_dataset/self_img/"#.jpg"
with open("custom_feature_model_dict.pkl","rb") as handle:
    model_dict = pickle.load(handle)
    
for i in range(16,17):
    
    lol = path+str(i)+".jpg"
    y_pred=predict_image(lol, model_dict["logistic"], le, True)
    
    if i==16:
        break

100%|██████████| 1/1 [00:00<00:00, 524.88it/s]


predicted_pose: ['Extended_Revolved_Triangle_Pose_or_Utthita_Trikonasana_']
getting cosine similarity results...


100%|██████████| 1/1 [00:00<00:00, 1956.30it/s]

dataframe saved with eval results!!


In [ ]:
import cv2
#from google.colab.patches import cv2_imshow
import math
import numpy as np
import mediapipe as mp
import pandas as pd
import os

def predict_image(model, path, le):
    
    mp_pose = mp.solutions.pose
    mp_drawing = mp.solutions.drawing_utils 
    mp_drawing_styles = mp.solutions.drawing_styles
    
    with mp_pose.Pose(static_image_mode=True, min_detection_confidence=0.5, model_complexity=2) as pose:
        
        img = cv2.imread(path)
     
        results = pose.process(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
      #add result to trainSet
        row = []
        for i in range(0,33):
            coord = results.pose_landmarks.landmark[i]
            row.append(coord.x)
            row.append(coord.y)
            row.append(coord.z)
            row.append(coord.visibility)
          #row.append(dict2[foldername])

    row = np.array(row).reshape(1,-1)
   # print(row)
    print((model.predict_proba(row)))
    print(le.inverse_transform(model.predict(row)))
    
#predict_image(model, "/home/hardeekh/Downloads/custom_dataset/self)img/", le)

In [ ]:
import glob
path = "/home/hardeekh/Downloads/custom_dataset/self_img/"
for file in glob.glob(os.path.join(path,"*")):
    
    with open(os.path.join(os.getcwd(),file),"r") as f:
        
        predict_image(model,f.name,le)
        
        
                   # cv2.imread(f.name)
        

/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.08 0.   0.05 0.4  0.02 0.2  0.15 0.05 0.01 0.04]]
['extended_side_angle']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.12 0.04 0.03 0.13 0.01 0.3  0.18 0.09 0.02 0.08]]
['seated_forward_bend']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.6  0.08 0.06 0.   0.13 0.01 0.06 0.   0.03 0.03]]
['cobra']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.01 0.04 0.   0.06 0.   0.   0.02 0.03 0.   0.84]]
['warrior-3']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.05 0.12 0.01 0.03 0.02 0.38 0.1  0.08 0.01 0.2 ]]
['seated_forward_bend']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.11 0.01 0.07 0.4  0.01 0.05 0.14 0.12 0.07 0.02]]
['extended_side_angle']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.09 0.29 0.06 0.03 0.   0.01 0.11 0.13 0.27 0.01]]
['dancer']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.28 0.01 0.01 0.07 0.01 0.21 0.34 0.03 0.03 0.01]]
['split']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.03 0.01 0.19 0.17 0.09 0.24 0.13 0.1  0.03 0.01]]
['seated_forward_bend']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.54 0.05 0.03 0.05 0.03 0.   0.16 0.01 0.11 0.02]]
['cobra']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.03 0.04 0.01 0.03 0.   0.   0.05 0.16 0.65 0.03]]
['warrior-2']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.48 0.05 0.03 0.1  0.03 0.03 0.17 0.02 0.05 0.04]]
['cobra']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.02 0.01 0.47 0.14 0.07 0.14 0.1  0.04 0.01 0.  ]]
['extended_revolved_triangle']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.01 0.   0.01 0.02 0.   0.36 0.45 0.12 0.01 0.02]]
['split']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


[[0.12 0.02 0.   0.16 0.   0.35 0.14 0.08 0.05 0.08]]
['seated_forward_bend']
[[0.   0.   0.2  0.61 0.06 0.05 0.04 0.01 0.02 0.01]]
['extended_side_angle']


/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/hardeekh/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
import glob
path = "/home/hardeekh/Downloads/custom_dataset/self_img/"
for file in glob.glob(os.path.join(path,"*")):
    
    with open(os.path.join(os.getcwd(),file),"r") as f:
        
        lol = predict_image(model,f.name,le)
        
        features = get_custom_features(lol)
        #print(lol)
        print(f.name)
        print((model.predict_proba(features)))
        print(le.inverse_transform(model.predict(features)))
                   # cv2.imread(f.name)
        

/home/hardeekh/Downloads/custom_dataset/self_img/9.jpeg
[[0.   0.34 0.23 0.33 0.06 0.02 0.01 0.   0.01 0.  ]]
['dancer']
/home/hardeekh/Downloads/custom_dataset/self_img/12.jpeg
[[0.03 0.73 0.12 0.06 0.01 0.04 0.01 0.   0.   0.  ]]
['dancer']
/home/hardeekh/Downloads/custom_dataset/self_img/14.jpeg
[[0.92 0.01 0.06 0.   0.   0.   0.01 0.   0.   0.  ]]
['cobra']
/home/hardeekh/Downloads/custom_dataset/self_img/7.jpeg
[[0.1  0.54 0.34 0.01 0.01 0.   0.   0.   0.   0.  ]]
['dancer']
/home/hardeekh/Downloads/custom_dataset/self_img/6.jpg
[[0.63 0.06 0.1  0.01 0.09 0.02 0.04 0.04 0.   0.01]]
['cobra']
/home/hardeekh/Downloads/custom_dataset/self_img/5.jpg
[[0.01 0.68 0.2  0.07 0.02 0.01 0.01 0.   0.   0.  ]]
['dancer']
/home/hardeekh/Downloads/custom_dataset/self_img/11.jpeg
[[0.15 0.07 0.18 0.23 0.31 0.   0.03 0.03 0.   0.  ]]
['half_moon']
/home/hardeekh/Downloads/custom_dataset/self_img/13.jpeg
[[0.13 0.08 0.12 0.09 0.03 0.46 0.07 0.02 0.   0.  ]]
['seated_forward_bend']
/home/hardeekh/D